language: python
python:
- '3.7'
branches:
  only:
    - master
    - dev
install:
- make setup
script:
- make test
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_TOKEN"
  app:
    master: "$APP_NAME"
  on:
    branch: master
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  global:
  - secure: "$API_ID"
  - secure: "$API_HASH"
  - secure: "$APP_NAME"
  - secure: "$SESSION_STRING"
  - secure: "$TOKEN"
  - secure: "$STICKERSET_ID"
  - secure: "$STICKERSET_HASH"
  - DEBUG=0
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
