language: python
python:
- '3.7'
install:
- make setup
script:
- make test
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_TOKEN"
  app:
    master: pugmabot
env:
  global:
  - secure: "$API_ID"
  - secure: "$API_HASH"
  - secure: "$APP_NAME"
  - secure: "$PORT"
  - secure: "$TOKEN"
  - secure: "$STICKERSET_ID"
  - secure: "$STICKERSET_HASH"
  - DEBUG=0
