name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: pugma-docker
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
