name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: python:3.7-slim-buster
 
    steps:
    - uses: actions/checkout@v1
    - name: pugma-docker
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
